tools/mctp-vdm-util-wrapper: change cache to use monotonic clock mechanism
mctp-vdm-util-wrapper cache currently uses the file time to determine cache age,
which is subject to realtime clock changes. If the system clock is set backwards,
the cache will be treated as fresh for as the same amount of time as the backwards
time adjustment, impacts detection of events that use this wrapper. Store the
monotonic time in the file instead to prevent the issue.

example file content: line 1 monotonic timestamp, line 2 RC code,
the rest is cached output:

    root@hgx:/tmp/zzz_deploy# cat /tmp/aml_mctp_cache/query_boot_status_17
    134299
    0
    Test command = query_boot_status
    teid = 17
    TX: 47 16 00 00 80 01 05 01
    RX: 47 16 00 00 00 01 05 01 00 00 00 01 FD 50 40 11 20

Test:

    root@hgx:/tmp# rm /tmp/aml_mctp_cache/*
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    cache for EID=14 is empty or stale, refilling it
    0
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    0
    root@hgx:/tmp# vi aml_mctp_cache/query_boot_status_14
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    Error: MCTP cmd for EC_TAG0_AUTH_ERROR on 14 failed, rc=33!
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    Error: MCTP cmd for EC_TAG0_AUTH_ERROR on 14 failed, rc=33!
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper --invalidate GPU_SXM_1
    Unknown test cmd
    Error: MCTP cmd for --invalidate on 14 failed, rc=1!
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper -invalidate GPU_SXM_1
    Cache manually invalidated for DEVNAME=GPU_SXM_1 EID=14
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper -invalidate GPU_SXM_1
    Cache manually invalidated for DEVNAME=GPU_SXM_1 EID=14
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    cache for EID=14 is empty or stale, refilling it
    0
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    0
    root@hgx:/tmp# vi aml_mctp_cache/query_boot_status_14
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    Error: MCTP cmd for EC_TAG0_AUTH_ERROR on 14 failed, rc=33!
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    Error: MCTP cmd for EC_TAG0_AUTH_ERROR on 14 failed, rc=33!
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper -invalidate GPU_SXM_1
    Cache manually invalidated for DEVNAME=GPU_SXM_1 EID=14
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    cache for EID=14 is empty or stale, refilling it
    0
    root@hgx:/tmp# DEV_EID_PROFILE="/usr/share/device_mctp_eid.csv" ./mctp-vdm-util-wrapper EC_TAG0_AUTH_ERROR GPU_SXM_1
    0

Fixes nvbug https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=4234277&cmtNo=

Signed-off-by: Szymon Pajchrowski <szymon.pajchrowski@conclusive.pl>